### ISSUE TITLE
Tree branches for CRT strips have different size in HitDumper module 

### ISSUE THREAD

**Issue by fjnicolas** [SBNSoftware/sbndcode#125]
In sbndcode/Commissioning/HitDumper_module.cc, line 517:

        _crt_time.push_back(ctime);
        _crt_adc.push_back(adc1 + adc2 - 127.2); // -127.2/131.9 correct for gain and 2*ped to get pe
        _crt_pos.push_back(center.Y());
        if (tagger.second == kCRTVertical) {
          _crt_pos.push_back(center.X());
        };

When the if statement "if (tagger.second == kCRTVertical)" is satisfied, the strip center position is saved twice (it first appends Y value, then X value) and the `_crt_*` vectors saved in the TTree have a different size.

Also in line 686 the number of CRT hits is not properly assigned (it currently loads the number of TPC hits):

    if (evt.getByLabel(fCRTHitModuleLabel, crtHitListHandle))  {
      art::fill_ptr_vector(chitlist, crtHitListHandle);
      _nchits = hitlist.size();
    }

**Comment by marcodeltutto** [comment]
Thanks @fjnicolas for spotting this! @astblake also pointed out this problem in an email. @astblake you mentioned you have a pull request to fix this?

**Comment by fjnicolas** [comment]
Great @marcodeltutto! Another point is that we may be interested in also saving the strip Z coordinate instead of X/Y depending on the CRT plane. For instance for the the east-west planes the X position of the strip is already known given the plane ID, and the Z would give us more information about the position of the triggered strip. Something like:

- 1. Front-back planes: save X (vertical strips) or Y (horizontal strips)
- 2. East-west planes: save Z (vertical) or Y (horizontal)
- 3. Top-bottom: save X or Z

I can work on a PR if people think this could be useful

**Comment by marcodeltutto** [comment]
Yes, definitely useful! Can we save X, Y, and Z for all planes? Then one of the three will be trivial depending on the plane, but in this way we save all of them in same way. Thanks!
