### ISSUE TITLE
GENIE Random Seed for CI Tests

### ISSUE THREAD

**Issue by henrylay97** [SBNSoftware/sbndcode#130]
We've had a long running issue in the CI system where the `nucosmics_gen` test occasionally (ball park 1 in 20 runs) produces 2 neutrino interactions (2 `MCTruth` objects) rather than one. An example of the CI output can be found [here](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2021/07/27/stdout%234A2CME7.log) at the end of this log.

The [fcl](https://github.com/SBNSoftware/sbndcode/blob/develop/test/ci/sbnd_ci_nucosmics_gen_quick_test_sbndcode.fcl) used to run this test specifies "perEvent" and a specific seed so should theoretically always produce the same output. A few people have had brief looks at locating the issue but nothing detailed.

This issue has become more pressing now as two attempts to update reference events have failed due to the _new_ reference files being produced with 2 `MCTruth`'s and therefore failing the immediate [ci_test checks](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2021/07/31/stdout%23eCKxZSU.log) and therefore not being replaced.

Am assigning anyone I've already discussed this with at any point for book keeping.

**Comment by vitodb** [comment]
By comparing the debug.log for the `nucosmics_gen` job used to generate the reference files and the corresponding job used to test the new reference I see there are differences in the seeds used by the random engine, I have the impression those seeds are set to `0`.

- Log for the reference generation
```
[...]
%MSG-d RANDOM:  ProcessEvent 31-Jul-2021 10:02:42 CDT run: 1 subRun: 0 event: 1
RNGservice::takeSnapshot_() of the following engine labels:
 | corsika:0:gen | corsika:0:pois |
[...]
%MSG-i NuRandomService:  CORSIKAGen:corsika@BeginModule  31-Jul-2021 10:02:42 CDT run: 1 subRun: 0 event: 1
Random seed for this event, engine 'corsika.gen': 760963931
%MSG
%MSG-i NuRandomService:  CORSIKAGen:corsika@BeginModule  31-Jul-2021 10:02:42 CDT run: 1 subRun: 0 event: 1
Random seed for this event, engine 'corsika.pois': 40438174
%MSG
%MSG-i CORSIKAGEN:  CORSIKAGen:corsika@BeginModule 31-Jul-2021 10:02:42 CDT  run: 1 subRun: 0 event: 1
 Shower input 0 with mean 44347.3 generating 44342
[...]
```
- Log for the reference check
```
[...]
RNGservice::takeSnapshot_() of the following engine labels:
 | corsika:0:gen | corsika:0:pois |
[...]
%MSG-i NuRandomService:  CORSIKAGen:corsika@BeginModule  31-Jul-2021 10:29:17 CDT run: 1 subRun: 0 event: 1
Random seed for this event, engine 'corsika.gen': 869657811
%MSG
%MSG-i NuRandomService:  CORSIKAGen:corsika@BeginModule  31-Jul-2021 10:29:17 CDT run: 1 subRun: 0 event: 1
Random seed for this event, engine 'corsika.pois': 851056619
%MSG
%MSG-i CORSIKAGEN:  CORSIKAGen:corsika@BeginModule 31-Jul-2021 10:29:17 CDT  run: 1 subRun: 0 event: 1
 Shower input 0 with mean 44347.3 generating 44341
[...]
```
It looks like also `single_gen` has the random engine set to `0`, but then both jobs, i.e. the one that generates the reference and the one that checks it, are getting the same seeds: 

- Log for the reference generation
```
[...]
%MSG-i RANDOM:  SingleGen:generator@Construction 31-Jul-2021 09:53:46 CDT  ModuleConstruction
Instantiated HepJamesRandom engine "generator:0:" with seed 0.
%MSG
%MSG-i NuRandomService:  SingleGen:generator@Construction  31-Jul-2021 09:53:46 CDT ModuleConstruction
Seeding  engine "generator:" with seed 0.
[...]
%MSG-i NuRandomService:  ProcessEvent 31-Jul-2021 09:53:48 CDT  run: 1 subRun: 0 event: 1
Random seed for this event, engine '.SBNDuBooNEDataDrivenNoiseService': 303357253
%MSG
%MSG-d RANDOM:  ProcessEvent 31-Jul-2021 09:53:48 CDT run: 1 subRun: 0 event: 1
RNGservice::takeSnapshot_() of the following engine labels:
 | generator:0: |

%MSG
%MSG-d ProductID:  RandomNumberSaver:rns@BeginModule 31-Jul-2021 09:53:48 CDT  run: 1 subRun: 0 event: 1
Product created with id: [1482339739] from canonical product name: "art::RNGsnapshots_rns__SinglesGen."
%MSG
%MSG-i NuRandomService:  SingleGen:generator@BeginModule  31-Jul-2021 09:53:48 CDT run: 1 subRun: 0 event: 1
Random seed for this event, engine 'generator': 37771392
%MSG
[...]
```

- Log for the reference check

```
[...]
%MSG-i RANDOM:  SingleGen:generator@Construction 31-Jul-2021 10:27:21 CDT  ModuleConstruction
Instantiated HepJamesRandom engine "generator:0:" with seed 0.
%MSG
%MSG-i NuRandomService:  SingleGen:generator@Construction  31-Jul-2021 10:27:21 CDT ModuleConstruction
Seeding  engine "generator:" with seed 0.
[...]
%MSG-i NuRandomService:  ProcessEvent 31-Jul-2021 10:27:22 CDT  run: 1 subRun: 0 event: 1
Random seed for this event, engine '.SBNDuBooNEDataDrivenNoiseService': 303357253
%MSG
%MSG-d RANDOM:  ProcessEvent 31-Jul-2021 10:27:22 CDT run: 1 subRun: 0 event: 1
RNGservice::takeSnapshot_() of the following engine labels:
 | generator:0: |

%MSG
%MSG-d ProductID:  RandomNumberSaver:rns@BeginModule 31-Jul-2021 10:27:22 CDT  run: 1 subRun: 0 event: 1
Product created with id: [1482339739] from canonical product name: "art::RNGsnapshots_rns__SinglesGen."
%MSG
%MSG-i NuRandomService:  SingleGen:generator@BeginModule  31-Jul-2021 10:27:22 CDT run: 1 subRun: 0 event: 1
Random seed for this event, engine 'generator': 37771392
[...]
```

Unfortunately those debug.log are not available from the CI dashboard, but I just added those to the list of logs to be uploaded, so they will be available for futures CI builds.
I attached here the ones for the  `nucosmics_gen` stage.
[nnucosmics_gen_test_sbndcode_debug.log](https://github.com/SBNSoftware/sbndcode/files/6918324/nnucosmics_gen_test_sbndcode_debug.log)
[nucosmics_gen_seq_test_sbndcode_debug.log](https://github.com/SBNSoftware/sbndcode/files/6918325/nucosmics_gen_seq_test_sbndcode_debug.log)

**Comment by vitodb** [comment]
Not sure if this is the cause of the seed issue, but it could contribute to it.
In the [ci_tests.cfg](https://github.com/SBNSoftware/sbndcode/blob/develop/test/ci/ci_tests.cfg) for the `[test nucosmics_gen_seq_test_sbndcode]` section there is 
[INPUT_STREAM=%(XROOTD_BASEFILEDIR_SBNDCODE)s/input/empty/EmptyEvents_01.root](https://github.com/SBNSoftware/sbndcode/blob/develop/test/ci/ci_tests.cfg#L745)
while for the `[test nucosmics_gen_quick_test_sbndcode]` section there is
[INPUT_STREAM=%(XROOTD_BASEFILEDIR_SBNDCODE)s/input/empty/EmptyEvents_02.root](https://github.com/SBNSoftware/sbndcode/blob/develop/test/ci/ci_tests.cfg#L587)
Maybe those tests should use the same input file to guarantee the same random engine seed configuration, shouldn't they?
This seems to be the case for the `single_gen` test configuration.

**Comment by PetrilloAtWork** [comment]
I confirm that the `perEvent` policy bases its random seeds on the timestamp of each event, therefore using two different `EmptyEvent` input files for input will generate different random seeds. The presence of different `EmptyEvent` was motivated precisely with the idea of having different seeds between jobs, but the sequence and quick jobs should share it.
Thus, the problem may be a common copy-and-paste issue.

But I somehow feel there is more going on. The output with seed `0` is the typical effect of `perEvent` policy (the seed is set at the beginning of the event, with all the sometimes nefarious consequences of it, but that printout happens outside any event).
I would have expected the other job, when correctly set up with `perEvent`, to do the same. So if the problem persists after the fix Vito suggests, this may be a track to follow.

**Comment by henrylay97** [comment]
Thank you both for looking at this so quickly! Vito makes a good point about the two different input files and I'll take a look at this tomorrow to see if this fixes our problem. I also feel there might be a little more to it though. 

If I understand what you've both said then having the two different input files should mean we see the difference between the _generation_ (or seq) and the _check_ (or quick) tests everytime. Whereas this error has been cropping up in a more random kind of way, suggesting the seed is not successfully set and is actually different each time?

**Comment by vitodb** [comment]
Yes, my take of the issue is that having the gen stage for the `seq` and the `quick` tests different input files, causes them to use different set of seeds.
The way reference files are generated and the way they are used by standard CI tests, can cause differences in `products` for the gen stage. However, given what information are provided by `products` we only noted this now because the two set of seeds used for the gen stage by `seq` and `quick` tests led to events with different number of `MCTruth` objects.
Possibly previously we still had different `MCTruth` objects, but their size was the same, so the difference between the `seq` and `quick` gen stage outputs was unnoticed.
I agree this could be just part of the issue, there could be more waiting.

**Comment by henrylay97** [comment]
I have created a [bugfix](https://github.com/SBNSoftware/sbndcode/tree/bugfix/ci_genie_seeding_error) branch which will ensure this consistency as the first check. I've tested it locally and confirms it ensures the same seeds for the lines Vito pointed out, I will PR this today to get this in. 

However, I'm even more convinced there is more to it as the product differences are specific to the Genie `MCTruth` objects (with `generator` tag) not the Corsika `MCTruth` (with `corsika` tag). By changing this input file I didn't see any changes to genie messages in the debug logs only the corsika messages. 

I know what you mean about the differences in product sizes, but we've seen this error historically every 20 builds or so in the `quick` test, which means the seed is not being consistently passed/used even within just the `quick` test.

**Comment by henrylay97** [comment]
The PR mentioned above has allowed us to update the reference files. However, at the first attempt the same warning cropped up again. So, as expected, there is something more fundamental broken in the way that the seeding is working.

**Comment by wesketchum** [comment]
Moving for further discussion for Oct (2021C) release.

**Comment by wesketchum** [comment]
@henrylay97 @chilge any update on this?
