### ISSUE TITLE
CRT Geometry in v02_00

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbndcode#137]
With the new geometry `v02_00`, the number of CRT auxiliary detectors returned by the GeometryService is 0. This likely has to do with the fact that the `physvol` name doesn't start with `volAuxDet`.

To quickly verify this behavior, with `sbndcode` set up:
```
python
import SBNDservices as serv
geom = serv.ServiceManager('Geometry')
geom.NAuxDets()
```
This returns:
- `142` with `sbndcode v09_24_00` (geometry `v01_05`).
- `0` with `sbndcode v09_28_00` (geometry `v02_00`).

**Comment by marcodeltutto** [comment]
Problem can be fixed by replacing 
`<physvol name="CRTPaddle_CRT_declaring_modules" [...]`
with
`<physvol name="volAuxDetCRTPaddle_CRT_declaring_modules" [...]`

With this change `NAuxDets()` is `2152`, as expected. 

But code now fails with 
```
  ---- CRTChannelMap BEGIN
    Wrong number of sensitive volumes for CRT volume volAuxDetSensitiveCRTStripY (got 1, expected 16)
  ---- CRTChannelMap END
```
because in the new geometry there is one sensitive volume per CRT module, not 16. 

Changes are needed to CRTChannelMap to be compatible with the new geometry.

**Comment by wesketchum** [comment]
Moving to 2021C production as per discussion in SBN AI meeting 10 Aug.

**Comment by wesketchum** [comment]
Assigning to @ilepetic and marking as in progress, as I believe there is a fix. When PR is made we should attach to this issue, and then close when all complete.
