### ISSUE TITLE
Shower calorimetry broken by PR 128 (view fix for the new geometry)

### ISSUE THREAD

**Issue by absolution1** [SBNSoftware/sbndcode#139]
The view fix for the new geometry has fixed many broken features in the reconstruction but it has had the unintended effect of negatively impacting the shower dE/dx reconstruction.

The working hypothesis is that the relevant module/algs in the shower reconstruction need a similar consistency fix as introduced in PR https://github.com/SBNSoftware/sbndcode/pull/128.

The 2021 production freeze should not go ahead until we have understood where the issue lies in the workflow.  If the problem occurs in the high-level reconstruction then this could be 'trivially' re-run post-production.  If the problem occurs earlier in the workflow then this should be fixed before the production gears start spinning.

Relevant plots can be found in a [recent CI run](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/6954&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_validation&buildtype=slf7%20e20:prof).

**Comment by wesketchum** [comment]
@absolution1 @etyley @henrylay97 any update on this?

**Comment by etyley** [comment]
I am just writing some slides for the meeting, but it seems like the fix that was put in to fix the signal shaped in PR 128 has indeed broken the shower calorimetry. We can discuss the best course of action in the meeting, as there does not appear to be a simple fix to this.
