### ISSUE TITLE
Flash matching does not work with XArapucas

### ISSUE THREAD

**Issue by pgreen135** [SBNSoftware/sbndcode#140]
Following the updates to the XArapuca simulation (https://github.com/SBNSoftware/sbndcode/pull/133) the flash matching no longer works for the XArapucas. It has been temporarily disabled (https://github.com/SBNSoftware/sbndcode/pull/138) until it can be fixed.

**Comment by wesketchum** [comment]
Attaching to the 'to-do' list for the fall release.

**Comment by wesketchum** [comment]
@rodralva @pgreen135 Is this issue now duplicated with #198 ? If so, we can close this one and just track this on the more recent one?
