### ISSUE TITLE
Swap induction planes in TPC 0 once View is fixed

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbndcode#142]
Pull request #141 swapped induction planes 0 and 1 in TPC 0. This was meant to be a temporary fix to the fact that the View was not being parser correctly and was creating problems down the road. We need to fix how the View is assigned in LArSoft, so we can undo the action taken in the PR #141. Moreover, we will need to check the code added with PR #128.

**Comment by wesketchum** [comment]
@marcodeltutto this will require a number of things from LArSoft to fix, correct? And likely not on timescale for 2021C? General/short update on this would be nice :)

**Comment by marcodeltutto** [comment]
@wesketchum correct, this is not on timescale for 2021C. I still need to contact the larsoft team to have a discussion on how to tackle this issue. I'll do it this week and keep this issue updated with any development.
