### ISSUE TITLE
Update CI reference files for v09_28_01

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbndcode#149]
Per #134, At minimum, new LArG4/geometry needs new reference files for standard fhicls to pass in CI:

* single_detsim_quick_test_sbndcode
* nucosmics_detsim_quick_test_sbndcode

Likely we want to do a more complete update of reference files.

Assigning to @chilge for now, who can I hope ask for updates elsewhere...

**Comment by henrylay97** [comment]
This is an ongoing process, we update the reference files whenever there are changes that give understood warnings, which at the moment averages once a week. As of last night the files are updated to reflect the 2021B production release :)
