### ISSUE TITLE
g4_no_opticalsim.fcl doesn't work with the new LArG4

### ISSUE THREAD

**Issue by VCLanNguyen** [SBNSoftware/sbndcode#153]
I got the following errors when running `g4_no_opticalsim.fcl`
` ServicesManager unable to find the service of type 'phot::PhotonVisibilityService'.`

**Comment by pgreen135** [comment]
the refactored LArG4 no longer uses the photon visibility service, so `services.PhotonVisibilityService: @erase` is likely the issue

**Comment by marcodeltutto** [comment]
Thanks @VCLanNguyen! I linked a PR that should solve this issue. I tested it and works for me, but please let me know if you'll have any trouble.
