### ISSUE TITLE
cafmakerjob_sbnd_sce.fcl doesn't work as part of standard workflow

### ISSUE THREAD

**Issue by jzennamo** [SBNSoftware/sbndcode#157]
When I run `cafmakerjob_sbnd_sce.fcl` after reco2 I get the below error. The input and log for the local test can be found here:
`/sbnd/app/users/jaz8600/AugustPrep/runtest`

```
%MSG-s ArtException:  PostEndJob 18-Aug-2021 11:50:41 CDT ModuleEndJob
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- ProductNotFound BEGIN
      Found zero products matching all selection criteria
        C++ type: std::vector<recob::Track>
        Module label: 'pandoraSCETrack'
        Product instance name: ''
        Process name: (empty)The above exception was thrown while processing module MCSFitAllPID/pandoraTrackMCS run: 1 subRun: 0 event: 1
    ---- ProductNotFound END
    Exception going through path runprod
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
---- DictionaryNotFound BEGIN
  No dictionary found for the following classes:

       art::Assns<sbn::Stub,recob::PFParticle,void>
       art::Wrapper<art::Assns<sbn::Stub,recob::PFParticle,void> >

  Most likely they were never generated, but it may be that they were generated in the wrong package.

  Please add (or move) the specification

       <class name="MyClassName"/>

  to the appropriate classes_def.xml file.

  Also, if this class has any transient members,
  you need to specify them in classes_def.xml.
---- DictionaryNotFound END
```

**Comment by jzennamo** [comment]
The specific fcl workflow, from sbndcode v09_28_01, I used is the following:

- prodoverlay_corsika_cosmics_proton_genie_fullosc_spill_gsimple-configh-v1_tpc.fcl
- standard_g4_sbnd.fcl 
- standard_detsim_sbnd.fcl 
- standard_reco1_sbnd.fcl 
- standard_reco2_sbnd.fcl 
- cafmakerjob_sbnd_sce.fcl

**Comment by jzennamo** [comment]
Casting a wide net here looking for some help @etyley @mendezdpatricia @gputnam @cjbackhouse @PetrilloAtWork @FernandaPsihas @ikatza @absolution1 @henrylay97 @hgreenlee 

My understanding of the issue is that currently `standard_reco2_sbnd .fcl` does not run pandora with SCE corrections applied , but the CAF stage isn't expecting that. It seems like we have three choices:
1. Run CAFs without SCE corrections
2. Add SCE corrections to `standard_reco2_sbnd.fcl`
3. Rerun Pandora with SCE corrections as part of `cafmakerjob_sbnd_sce.fcl`

**Comment by jzennamo** [comment]
I thought that I might just be able to substitute "reco2_sce.fcl" for "standard_reco2_sbnd.fcl" but that doesn't work because `reco2_sce.fcl` seg faults after or at "FlashPredict:  FlashPredict:fmatch@BeginModule"

**Comment by jzennamo** [comment]
If I remove `opt0finder` and `opt0finderSCE` I am able to run `reco2_sce.fcl`

**Comment by jzennamo** [comment]
Then the CAF file creation fails because the SimChannels had their producer changed to `sim::SimChannels_simdrift`

**Comment by jzennamo** [comment]
OK! We're getting somewhere, I think we'll need to update for the new LArG4
`/cvmfs/larsoft.opensciencegrid.org/products/larsim/v09_14_03/job/backtrackerservice.fcl`

**Comment by ikatza** [comment]
> The specific fcl workflow, from sbndcode v09_28_01, I used is the following:
> 
> * prodoverlay_corsika_cosmics_proton_genie_fullosc_spill_gsimple-configh-v1_tpc.fcl
> * standard_g4_sbnd.fcl
> * standard_detsim_sbnd.fcl
> * standard_reco1_sbnd.fcl
> * standard_reco2_sbnd.fcl
> * cafmakerjob_sbnd_sce.fcl

I believe this is the issue. To get SCE you need to run the SCE fcl versions starting from g4. Namely:
- g4_sce.fcl
- detsim_sce.fcl
- reco1_sce.fcl
- reco2_sce.fcl

**Comment by ikatza** [comment]
For the stages you ran, you want to use `cafmakerjob_sbnd.fcl` (no SCE)

**Comment by jzennamo** [comment]
OK, I guess that means the "standard" moniker on the above fcls isn't entirely accurate since I suppose we'd like to have SCE simulated, we'll update the workflows to use these "sce" fcls

Thanks @ikatza!

**Comment by jzennamo** [comment]
When doing as @ikatza suggested I am still getting seg fault at reco2, and am getting an incredibly large number of these errors:
`Error: Invalid optical detector type. 0 = rectangular, 1 = dome, 2 = disk. Or corrections for chosen optical detector type missing.`

**Comment by pgreen135** [comment]
you're seeing that error at reco2? that is from the fast optical simulation missing the parameterisations and hence not working, should only appear in the g4 stage as far as I understand

**Comment by jzennamo** [comment]
I am seeing that error when running `reco2`

**Comment by pgreen135** [comment]
maybe this is related to the flash matching then @ikatza?

**Comment by jzennamo** [comment]
yeah, I also get this intermittent error:

```
 %MSG
%MSG-w SBNDOpT0Finder:  SBNDOpT0Finder:opt0finder@BeginModule  19-Aug-2021 11:13:19 CDT run: 1 subRun: 0 event: 1
Zero good flashes in this event.
%MSG
Segmentation fault
```

**Comment by pgreen135** [comment]
possibly the flash matching is not correctly calling / configuring the light simulation functions now in the new larg4 when its making predictions, as its done differently compared with the legacy

**Comment by jzennamo** [comment]
I dropped optT0Finder and it seems to work

**Comment by ikatza** [comment]
> When doing as @ikatza suggested I am still getting seg fault at reco2, and am getting an incredibly large number of these errors:
> `Error: Invalid optical detector type. 0 = rectangular, 1 = dome, 2 = disk. Or corrections for chosen optical detector type missing.`

I don't think this mine. I believe this error comes from larsim. The exception doesn't say which module is printing it?

**Comment by pgreen135** [comment]
it comes from PDFastSimPAR in larsim, but isn't an issue there as the g4 stage runs without a problem (right?); what calls PDFastSimPAR in reco2?

**Comment by ikatza** [comment]
`OpT0Finder` @marcodeltutto

**Comment by jzennamo** [comment]
@etyley Looks like Razzel and Dazzel had a hardcoded call to largeant for simchannels, I am fixing now that

**Comment by etyley** [comment]
It should just require a fcl parameter change, nothing should be hardcoded

**Comment by jzennamo** [comment]
This is fixed in these PRs:
https://github.com/SBNSoftware/sbncode/pull/167
https://github.com/SBNSoftware/sbndcode/pull/162
https://github.com/SBNSoftware/sbnanaobj/pull/25

and with that I think it is all working now!
