### ISSUE TITLE
Seg faults when running g4 stage in recent sbndcode versions

### ISSUE THREAD

**Issue by henrylay97** [SBNSoftware/sbndcode#165]
As discussed offline, I have discovered a seg fault issue when running the g4 stage in sbndcode `v09_28_01` onwards. This corresponds to the migration to the new larg4 via PR #134. The seg fault occurs sporadically in genie samples (~1/600 events) but far more often in an overlay sample (~1/50 events). This wasn't picked up by the CI due to its low-ish frequency.

The back trace leads to the following [line](https://github.com/LArSoft/larsim/blob/develop/larsim/MCSTReco/MCRecoPart.cxx#L156) in a larsim file used by `mcreco`. The segfault occurs when trying to read a position from an MCParticle.

Adding print statements and looking at a single example I found the MCParticle in question to be a muon which could yield the following information:
`` Track ID: 158 PDG: 13 Mother: 0 Process:``
before segfaulting.

Reading further up the output, this muon with the same track ID exists earlier, i.e. it has already been looped over. However, previously it does contain a process (primary) and doesn't seg fault when asked for its position.

These seg faults are occurring using either the `standard_g4_sbnd.fcl` or `g4_sce.fcl`.

**Comment by pgreen135** [comment]
there is now a larsoft PR that fixes this issue: https://github.com/LArSoft/larg4/pull/24

**Comment by henrylay97** [comment]
The above PR has been merged. We're all clear with the prof builds but debug builds are still failing at g4 at the assert on [this](https://github.com/LArSoft/larg4/blob/develop/larg4/pluginActions/ParticleListAction_service.cxx#L778) line:

``assert(p.NumberTrajectoryPoints() != 0ull);``

CI logs can be found [here](https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/test_details?build_id=sbnd_ci/7099&platform=Linux%203.10.0-1160.31.1.el7.x86_64&buildtype=slf7%20e20:debug&phase=ci_tests&test=nucosmics_g4_quick_test_sbndcode) for e20:debug.
