### ISSUE TITLE
Large number of "Can't find nearest wire for position (x,y,z)" errors when running refactored larg4

### ISSUE THREAD

**Issue by pgreen135** [SBNSoftware/sbndcode#174]
There are a large number of the following message when running the g4 stage since the change to the new geometry and refactored larg4:

```
%MSG-w SimDriftElectrons:  SimDriftElectrons:simdrift@BeginModule  06-Sep-2021 02:29:44 CDT run: 1 subRun: 0 event: 1
unable to drift electrons from point (117.305,203.314,1.21832) with exception ---- Geometry BEGIN
Can't find nearest wire for position (201.75,203.385,1.27117) in plane C:0 T:1 P:1 approx wire number # 0 (capped from -17)
---- Geometry END
%MSG
```

If this isn't actually an issue, the messages need to be suppressed as they are swamping everything else --- e.g. there is ~700,000 lines of this in a recent CI test log: https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/storage/docs/2021/09/06/stdout%23zPg0ktQ.log

**Comment by pgreen135** [comment]
I notice that issue has been open for ~ 1 month -- if this is a longer term project could these be demoted to a debug message in the near term until it is fixed properly? the large number of messages can be a nuisance, e.g. in this distance making it difficult to load the logs from the CI test to identify the cause of a failure

**Comment by marcodeltutto** [comment]
I asked in the larsoft thread, I agree with you the logs are too heavy with all these messages.

**Comment by pgreen135** [comment]
these messages have now been demoted to debug only as of larsoft v09_30_00, although the underlying issue has not yet been resolved

**Comment by jzennamo** [comment]
Awesome! @marcodeltutto I think this can be closed then?

**Comment by marcodeltutto** [comment]
Yes, let's close it, thanks!
