### ISSUE TITLE
Wrong Offsets in MergeSimSources for Rolled Up Track IDs

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbndcode#191]
@etyley pointed out a bug in the MergeSimSources (larsoft issue [25525](https://cdcvs.fnal.gov/redmine/issues/25525)):

> When the offset is applied to the TrackID when using the LArSim module MergeSimSources the offset is applied both to the primary track Id and the "rolled up" track Id that is the negative of the original track Id [...] This breaks a symmetry that is assumed by many truth matching utilities

**Comment by wesketchum** [comment]
@etyley , would this be sufficient:

```
if(edep.TrackID() < 0) new_trackid = edep.TrackID()-offset; 
else new_trackid = edep.TrackID()+offset;
```

**Comment by marcodeltutto** [comment]
I think that would do it for the SimEnergyDeposit, and then we would have to do a similar thing for MCParticles and SimChannels. The only annoying thing is that fixing the offset for SimChannels requires changes to `SimChannel` itself, as the offset is used here:
https://github.com/LArSoft/lardataobj/blob/573ba5ef6613f418bfc139cf1bd8a857c4787212/lardataobj/Simulation/SimChannel.cxx#L307

**Comment by etyley** [comment]
I agree with Marco that the fix should be that simple but the structure of the code means the implementation needs to occur in many places, annoyingly across different repositories. In addition to the energy depositions, MCParticles and SimChannels, I assume that this also affects the SimPhotons(Lite) but I have not checked this.

**Comment by wesketchum** [comment]
@marcodeltutto and @etyley : just to confirm, we need this fixed for upcoming production, yes? If so, I can assign myself and try to get this done ASAP.

**Comment by wesketchum** [comment]
OK, associated PRs are in ... 

@etyley or @marcodeltutto , if you have a simple way to test to see if this looks like it fixes things, let me know and I can run such a test.

* nusimdata: https://github.com/NuSoftHEP/nusimdata/pull/2
* lardataobj: https://github.com/LArSoft/lardataobj/pull/18
* larsim: https://github.com/LArSoft/larsim/pull/77

**Comment by marcodeltutto** [comment]
Thank you @wesketchum!

**Comment by etyley** [comment]
Apologies for the late reply @wesketchum, I have been at a workshop this week. This is definitely required for both the in-time cosmics and dirt workflows we are hoping to incorporate into the upcoming production, so thanks for looking into this.

Any validation of this, other than simply plotting the trackIDs of each of the IDEs and particles, is going to be complicated by https://github.com/SBNSoftware/sbndcode/issues/202. Normally I would suggest checking the completeness for a sample of electrons before and after adding an offset with this module (there are relevant modules in sbnci) but any issues arising from such a test would likely be obfuscated by the aforementioned issue.

**Comment by wesketchum** [comment]
LArSoft PRs were merged in, so closing this issue.
