### ISSUE TITLE
OpHitFinder does not work with (Daphne)XArapucas

### ISSUE THREAD

**Issue by rodralva** [SBNSoftware/sbndcode#198]
This issue is related with the one pointed out by @ikatza  (#140) for FlashMatch. 
 
As far as i know, flash finder algorithms use [OpHits](https://nusoft.fnal.gov/larsoft/doxsvn/html/classrecob_1_1OpHit.html) as inputs. To compute the Ophits, algorithms look for peaks in the [raw simulated waveforms](https://nusoft.fnal.gov/larsoft/doxsvn/html/classraw_1_1OpDetWaveform.html).

In SBND we have 2 readout frequencies in the Optical System (500MHz/2ns for PMTs, 80MHz/12.5ns for Daphne XArapucas). The current SBND Optical Hit Finder [only considers](https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/OpDetReco/OpHit/SBNDOpHitFinder_module.cc#L216) the default OpticalClock (500MHz) set for PMTs, and then gives this info to [larana algorithms](https://github.com/SBNSoftware/larana/blob/develop/larana/OpticalDetector/OpHitFinder/OpHitAlg.cxx#L29) calling the [RunHitFinder](https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/OpDetReco/OpHit/SBNDOpHitFinder_module.cc#L230) function.

Simulated waveforms with daphne readouts have different number of bins, tick period... which results in miscalculations in the OpHits times and areas (PE). 

I'm working on this, modifying the SBND HitFinder so larana remains unchanged.

**Comment by pgreen135** [comment]
Following https://github.com/SBNSoftware/sbndcode/pull/216 this has been (mostly) resolved. The remaining issues are documented in https://github.com/SBNSoftware/sbndcode/issues/225, so I will close this.
