### ISSUE TITLE
Energy deposits from rolled up EM showers are still saved with their original G4ID in the refactored larg4

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbndcode#202]
Opening this issue here to keep track of larsoft issue [26294](https://cdcvs.fnal.gov/redmine/issues/26294) by @henrylay97.

**Comment by wesketchum** [comment]
@marcodeltutto any update on this from Kyle/Hans? And needed for 2021C or no?

**Comment by henrylay97** [comment]
I would say its pretty critical for 2021C, if we want to do any sensible truth matching in analysis work, particularly for electron based studies. 

There are kind of two options as I see it:
- this gets fixed and roll up works fine
- we run the production with the fcl parameter `keepEMShowerDaughters` set to true and perform the roll up in analysis rather than simulation. This is do-able but especially for cosmic productions I imagine this would add a huge amount of time / memory usage.

**Comment by cjbackhouse** [comment]
The current Icarus CAFs are very slow to use, I think because of huge amounts of non-rolled-up truth. So if fixing this at "analysis" time I think you would have to do it in CAFMaker, not literally in the analysis macros.

**Comment by henrylay97** [comment]
Even more of a reason to not want to do this I suppose!

**Comment by jzennamo** [comment]
`keepEMShowerDaughters == true` increases the file sizes incredibly for ICARUS so I am not keen on that solution, could we set up a meeting with Kyle/Hans to discuss the importance of fixing this for the Nov release?

**Comment by marcodeltutto** [comment]
@jzennamo Yes, I can send them an email and keep you all in the loop.

**Comment by wesketchum** [comment]
Thanks @marcodeltutto. Since you're taking the lead on coordinating this I'm going to assign this to you (want to try to assign things), but appreciate that it's an external need...

**Comment by henrylay97** [comment]
What is our plan for dealing with this given no fix was present in this week's LArSoft release?

**Comment by henrylay97** [comment]
> The current Icarus CAFs are very slow to use, I think because of huge amounts of non-rolled-up truth. So if fixing this at "analysis" time I think you would have to do it in CAFMaker, not literally in the analysis macros.

I'm happy to look into applying this in CAFMaker but it would require us to simulate with roll-up turned off which will have a huge impact on g4 run time & memory.

**Comment by jzennamo** [comment]
@wesketchum reached out to the LArSoft team to understand where this fix stands

**Comment by pgreen135** [comment]
Now resolved -- https://cdcvs.fnal.gov/redmine/issues/26294
