### ISSUE TITLE
Repository order inferred by mrb

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbndcode#205]
I have been having trouble building `sbndcode` together with another larsoft package. If I download `sbndcode` and, say, `larsim`, I noticed that the order in the top-level `CMakeLists.txt` is not correct, meaning that it attempts to build `sbndcode` before `larsim`, and this fails. 

Steps to reproduce:
```bash
source /cvmfs/sbnd.opensciencegrid.org/products/sbnd/setup_sbnd.sh
setup mrb
export MRB_PROJECT=larsoft
setup sbndcode v09_35_00 -q e20:prof
mrb newDev
source localProducts_larsoft_v09_35_00_e20_prof/setup
cd srcs/
mrb g -t v09_35_00 sbndcode
mrb g -t LARSOFT_SUITE_v09_35_00 larsim
# Order in CMakeLists.txt is *not* correct
mrb uc
# Order in CMakeLists.txt is correct
cd $MRB_BUILDDIR
mrbsetenv
# Order in CMakeLists.txt is *not* correct
mrb uc
# Order in CMakeLists.txt is *not* correct
mrb i
# Fails at configuration stage, as the order is wrong
mrb checkDeps
# Returns nothing, no visible action is taken
```

I need to fix `CMakeLists.txt` manually to build.

@pgreen135 do you know if we need to fix something in our ups file to have the dependecies right?

**Comment by etyley** [comment]
I also came across this behaviour which seemed to start with the new version of `mrb`. In order to get it to build I had to install all of the repositories that are built on top of larsim (`ups depend` tells you the intermediate repositories). I think @miquelnebot has been in touch with the LArSoft team about this?

**Comment by marcodeltutto** [comment]
Right, thanks @etyley! I think that is the solution in fact, but I'd like to avoid installing all repos if I need to modify just one (although I understand how this could create inconsistent builds...). 

Apparently the command `mrb checkDeps` should automatically verify if anything is missing and check out missing packages, but if I try to run it it does nothing for me.
