### ISSUE TITLE
Unexplained OpHit / OpFlash product differences in CI tests following larana#14

### ISSUE THREAD

**Issue by pgreen135** [SBNSoftware/sbndcode#213]
Several unexplained Reco1 product differences related to the OpHits and OpFlashes were picked up by the SBND CI tests following https://github.com/LArSoft/larana/pull/14 that made changes to the OpHitFinder for ICARUS (from Kazu). 

Full details from CI can be found here: https://dbweb8.fnal.gov:8443/LarCI/app/ns:sbnd/build_detail/phase_details?build_id=sbnd_ci/7640&platform=Linux%203.10.0-1160.31.1.el7.x86_64&phase=ci_tests&buildtype=slf7%20e20:prof 

@henrylay97 and I are investigating, have reached out to Kazu directly via slack and are awaiting a response. This needs to be understood/resolved before the production freeze.

**Comment by henrylay97** [comment]
In order to ease with code checks of the many PRs currently being tested for MCP2021C we have updated the reference files to reflect this and a few other changes (the other changes are expected and understood. This issue acts as a reminder to ensure we see that the reverse changes happen when this is fixed. Or that the changes are understood.

Changes in nucosmics_reco1:
```676: Compare products sizes for nucosmics_reco1_test_sbndcode_Current.root output stream.
677: 
678: 
679: Check for differences in the size of data products
680: difference(s)
681: 
682: 47c47
683: < Reco1 | opflashtpc0 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 21749
684: ---
685: > Reco1 | opflashtpc0 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 21742
686: 49c49
687: < Reco1 | opflashtpc1 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 21418
688: ---
689: > Reco1 | opflashtpc1 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 21408
690: 51c51
691: < Reco1 | ophitarapuca |  | std::vector<recob::OpHit> | 533
692: ---
693: > Reco1 | ophitarapuca |  | std::vector<recob::OpHit> | 246
694: 54c54
695: < Reco1 | ophitpmt |  | std::vector<recob::OpHit> | 44033
696: ---
697: > Reco1 | ophitpmt |  | std::vector<recob::OpHit> | 44015
698: 101c101
699: < Reco1 | opflashtpc0 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 16614
700: ---
701: > Reco1 | opflashtpc0 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 16621
702: 103c103
703: < Reco1 | opflashtpc1 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 25464
704: ---
705: > Reco1 | opflashtpc1 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 25481
706: 105c105
707: < Reco1 | ophitarapuca |  | std::vector<recob::OpHit> | 562
708: ---
709: > Reco1 | ophitarapuca |  | std::vector<recob::OpHit> | 307
710: 108c108
711: < Reco1 | ophitpmt |  | std::vector<recob::OpHit> | 42808
712: ---
713: > Reco1 | ophitpmt |  | std::vector<recob::OpHit> | 42832
```
Changes in single_reco1:
```
611: Check for differences in the size of data products
612: difference(s)
613: 
614: 41c41
615: < Reco1 | opflashtpc0 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 3409
616: ---
617: > Reco1 | opflashtpc0 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 3412
618: 45c45
619: < Reco1 | ophitarapuca |  | std::vector<recob::OpHit> | 75
620: ---
621: > Reco1 | ophitarapuca |  | std::vector<recob::OpHit> | 50
622: 48c48
623: < Reco1 | ophitpmt |  | std::vector<recob::OpHit> | 3615
624: ---
625: > Reco1 | ophitpmt |  | std::vector<recob::OpHit> | 3618
626: 91c91
627: < Reco1 | opflashtpc1 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 3297
628: ---
629: > Reco1 | opflashtpc1 |  | art::Assns<recob::OpHit,recob::OpFlash,void> | 3296
630: 93c93
631: < Reco1 | ophitarapuca |  | std::vector<recob::OpHit> | 41
632: ---
633: > Reco1 | ophitarapuca |  | std::vector<recob::OpHit> | 31
634: 96c96
635: < Reco1 | ophitpmt |  | std::vector<recob::OpHit> | 3485
636: ---
637: > Reco1 | ophitpmt |  | std::vector<recob::OpHit> | 3484
```

**Comment by jzennamo** [comment]
As a follow-up, it looks like LArSoft/larana#14 is supposed to add a flag "CatchSaturation" when I fiddle that flag it doesn't change the number of ophits reco'ed

**Comment by jzennamo** [comment]
@pgreen135 pointed out that there is a change in that the thresholds are now hardcoded:
```
   -if (local_rms < _threshold) {
   +if (local_mean_v[i] > -0.1) {
```
https://github.com/LArSoft/larana/pull/14/files#diff-0c4189a514da722a0ba987f3ea92657435e2141356665b91261d645d4e98f29eL326-R345

**Comment by wesketchum** [comment]
OK, trying to sum up possible changes...

https://github.com/LArSoft/larana/compare/LARSOFT_SUITE_v09_35_00..LARSOFT_SUITE_v09_35_01

* `_threshold` parameter is not used in spots, and has been replaced by a local_mean check to be >-0.1 instead (noted by @pgreen135)
* calculation of local_mean and local_rms now centers around a pre- and post-sample ... not sure if that is compensated later or not (I couldn't tell)
* saturation correction, but I do think this is properly handled to default to previous behavior, excepting the potential things above

@lgarren @knoepfel about to send an email, but FYI ...

**Comment by drinkingkazu** [comment]
Thanks for finding this!

If helpful, I am happy to take a look if you could provide me a larsoft file w/ waveforms to run ophit finder (and preferably has nothing else that complains on persistency like required geometry etc...).

**Comment by pgreen135** [comment]
To keep track, LArSoft issue corresponding to this: https://cdcvs.fnal.gov/redmine/issues/26421

**Comment by pgreen135** [comment]
@drinkingkazu you can use this detsim file from Henry for testing: `/sbnd/data/users/hlay/for_joe/single_detsim_test_sbndcode_Reference-202110260652.root` 

This was made with the sbnd geometry, using sbndcode v09_35_01

**Comment by pgreen135** [comment]
larana#14 has now been reverted (https://github.com/LArSoft/larana/pull/16), so I will close this issue
