### ISSUE TITLE
Propagation times for scintillation photons produced in the outer volume are not simulated

### ISSUE THREAD

**Issue by fjnicolas** [SBNSoftware/sbndcode#219]
The refactored larg4 cannot use (it is "broken" at the moment) the transport time model + library.  This means that propagation times are not simulated/included for scintillation photons produced in the OUT-TPC volume (only emission time is considered). An example can be seen in the plot (averaged photon arrival times for nu-mu events at x~100 cm for both light components):

<img width="492" alt="Captura de pantalla 2021-11-10 a las 10 18 19" src="https://user-images.githubusercontent.com/66068208/141850252-7994035b-1984-4ec0-9542-7d878d44690f.png">

The first bunch of arrival photons is not correct (clearly visible for the case of the Reflected/Viisible light component in the figure). This bug may affect downstream reconstruction chain (for instance it can fake OpFlash t0). 

From conversation with @pgreen135, @therealendrju and @ggamezdiego we think we should turn-off “pdfastsimout” until this problem is fixed (unfortunately not before this MC production). If everyone agrees I can proceed with the PR for the turning-OFF the OUT-TPC simulation.

**Comment by marcodeltutto** [comment]
Hi @fjnicolas, great you found this issue! I agree with you that we should disable this for now.

**Comment by pgreen135** [comment]
Re-opening this issue to keep track of. The optical hybrid has now been disabled until this can be fixed. The changes needed are related to those needed for https://github.com/SBNSoftware/sbndcode/issues/163, I will assign myself to this

**Comment by pgreen135** [comment]
@fjnicolas I have done the necessary restructuring in larsim to allow the propagation times to be simulated with the library. The branches are (both based on v09_37_01):

https://github.com/pgreen135/larsim/tree/feature/pgreen_semianalyticmodel_refactor
https://github.com/SBNSoftware/sbndcode/tree/feature/pgreen_hybrid_model_propagation_times

could you check that this resolves this issue?

**Comment by fjnicolas** [comment]
Looks good! This is the plot I obtain for the SimPhotons arrival time distribution for muon neutrinos at <X>~170 [cm] without the larsim restructuring (left) and with the modifications (right). The `ionandscint` and `ionandscintout` inputs are the same in both cases.

<img width="679" alt="plot1" src="https://user-images.githubusercontent.com/66068208/144135630-52f5f5b0-8463-4874-ba78-4752a47e20fb.png">

Same plots for neutrinos at <X>~40 [cm]
<img width="679" alt="plot2" src="https://user-images.githubusercontent.com/66068208/144135612-4ff93a26-2604-4440-8d05-4493e9b279db.png">

**Comment by pgreen135** [comment]
Thanks for running these tests @fjnicolas!
