### ISSUE TITLE
CRT: MeV vs GeV units for IDE

### ISSUE THREAD

**Issue by ilepetic** [SBNSoftware/sbndcode#252]
The GenericCRT module outputs IDEs in MeV, while the SBND CRT detsim expects GeV. This causes the SiPMs to be always record maximum values.

PR https://github.com/LArSoft/larsim/pull/86 resolves this and should be added to the SBN 2022A release.

**Comment by henrylay97** [comment]
@pgreen135 no this was only found after 2021C was launched. There will however be a CRT related PR from myself to sbndcode for the 2022A release. I will get this done as soon as I can :)

**Comment by pgreen135** [comment]
@henrylay97 okay, thanks
