### ISSUE TITLE
Set SAM_EXPERIMENT=sbn by default

### ISSUE THREAD

**Issue by cjbacchus** [SBNSoftware/sbndcode#260]
Now that the SAM databases are unified, we should set `SAM_EXPERIMENT=sbn` in the default setup. This will make the samweb command-line tool, and CAFAna's SAM infrastructure, work out of the box. This is set by `/cvmfs/sbnd.opensciencegrid.org/products/sbnd/setup_sbnd.sh`, but I'm not sure where (if anywhere?) that is version controlled.

**Comment by cjbackhouse** [comment]
See also https://github.com/SBNSoftware/icaruscode/issues/339

**Comment by pgreen135** [comment]
That is a very good question, as far as I am aware the setup scripts are not version controlled, so I am not sure the best way to go about changing this in a backward compatible way. I guess it could be done with a check against the version number in the script?
