### ISSUE TITLE
LArG4 EnergyCut

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbndcode#261]
In the LegacyLArG4 we had the kinetic energy cut for particle tracking set to `1e-5`, assuming it’s GeV, so `1e-5 GeV = 10 keV`.
The problem is that the new LArG4 assumes the unit is MeV, `1e-5 MeV = 10 eV`, so we are applying a 10 eV cut on particle tracking. We usually consider this too low, at least for general production.

We should:

- [x] change the `1e-5` to `1e-2` in https://github.com/SBNSoftware/sbndcode/blob/ac330b04d4571bf08f09db91169034a378f5eaa1/sbndcode/LArG4/larg4_services_sbnd.fcl#L44
- [x] inquire on the new behavior of LArG4 (using MeV instead of GeV) check it is intentional, and if not request that this be changed in LArG4.

**Comment by wesketchum** [comment]
@marcodeltutto , if we can close this issue (and merge the discussion on behavior elsewhere, either a new issue or ... etc.) that would be great.
