### ISSUE TITLE
Single PE Test Bench Waveform Vector

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbndcode#28]
The single PE waveform vector from the test bench measurement is stored in `sbnd_data` in `OpDetSim/digi_pmt_sbnd.root` with name `SinglePEVec`.

In https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/OpDetSim/DigiPMTSBNDAlg.cc#L48 is retrieved with name `SinglePEWave`, which causes a segmentation fault.

**Comment by ikatza** [comment]
Ups yeah my fault, forgot to rename a variable. PR #29 fixes this.
