### ISSUE TITLE
Update refactored branch of sbndcode to the target version

### ISSUE THREAD

**Issue by PetrilloAtWork** [SBNSoftware/sbndcode#30]
The refactored branch `feature/repositoryRestructuring` is branched from `v08_57_00`.
If that is the branch for the final refactoring, it needs to be updated to the target version for refactoring (if not, the correct branch needs the same update).
There _might_ be other `sbndcode` branches that need to be integrated/merged together. I am not aware of any other.

**Comment by ascarff** [comment]
I think this can be closed now. The restructured repo is now in develop and up to date with the latest version of LArSoft.
