### ISSUE TITLE
Rare vector length issue in X-Arapuca flash reconstruction

### ISSUE THREAD

**Issue by henrylay97** [SBNSoftware/sbndcode#322]
We have not run a large scale production since the inclusion of xarapuca reconstruction. I was producing a sample of files using `sbndcode v09_67_00` . I ran into an issue that only cropped up in a handful of events in a sample of 10,000 events. Hence, why the CI did not pick this up.

I was using a standard set of production files (nu + dirt + cosmic).

> prodoverlay_corsika_cosmics_proton_genie_rockbox_sce.fcl
> g4_sce_dirt_filter_lite.fcl
> detsim_sce_lite.fcl
> reco1_sce_lite.fcl
> reco2_sce_no_opt0finder.fcl

The issue occurs at the reco1 stage and provides the following output:
```

%MSG-s ArtException:  PostEndJob 03-Mar-2023 16:15:48 UTC ModuleEndJob
---- EventProcessorFailure BEGIN
  EventProcessor: an exception occurred during current event processing
  ---- ScheduleExecutionFailure BEGIN
    Path: ProcessingStopped.
    ---- StdException BEGIN
      An exception was thrown while processing module SBNDFlashFinder/opflashtpc0xarapuca run: 1 subRun: 20 event: 184
      vector::_M_range_check: __n (which is 48728) >= this->size() (which is 6296)
    ---- StdException END
    Exception going through path reco1
  ---- ScheduleExecutionFailure END
---- EventProcessorFailure END
---- FatalRootError BEGIN
  Fatal Root Error: TTree::SetEntries
  Tree branches have different numbers of entries, eg recob::OpFlashrecob::OpHitvoidart::Assns_opflashtpc1xarapuca__Reco1. has 24 entries while EventAuxiliary has 43 entries.
  ROOT severity: 2000
---- FatalRootError END
%MSG
Art has completed and will exit with status 1.
```

You can reproduce this error by setting up sbndcode v09_67_00 and running:
`lar -c reco1_sce_lite.fcl -s /pnfs/sbnd/scratch/users/hlay/crt/debug_opflash_arapucas/detsim/57441609_19/prodgenie_cosmic_rockbox_sbnd_GenieGen-20230302T190902_G4-20230302T193859_DetSim-20230302T195820_c8d19e83-a5eb-4511-8754-c3744b3dfb5e.root -n 1 --nskip 24`

In all scenarios the error was the same (different event, different size, different n, but same underlying issue).

I've alerted @fjnicolas (and through him @rodralva as well) but we'll open this issue to keep tabs on it and point people at if they have the same problem.

**Comment by fjnicolas** [comment]
Thanks @henrylay97 for spotting this and providing the input to reproduce the error! Some static vectors were not properly reset. SBNSoftware/sbndcode#323 solves it.

**Comment by fjnicolas** [comment]
Closing the issue with #323.
