### ISSUE TITLE
opDetDigitizerWorker only creates a waveform if there are REFLECTED photons arriving to the PMTs

### ISSUE THREAD

**Issue by fjnicolas** [SBNSoftware/sbndcode#34]
In some events, there are some OpCh with SimPhotonsLite saved but no waveforms built.

The problem is in OpDetSim/opDetDigitizerWorker.cc and how the waveforms are created. In the PMTs case, the module only creates a waveform (if conditional in lines 164-165) if there are REFLECTED photons arriving the OpChannels (direct photons are added later to the waveform, but only if there is at least one reflected SimPhoton in the channel).
There may be some events (generally those near the PDS/further from the TPB foils) in which there are plenty of direct photons arriving the PMTs, but no reflected ones. Hence no waveform is built, though there are a lot of direct photons reaching the OpCh.

**Comment by ikatza** [comment]
Great find @fjnicolas!

Note that same faulty logic for the case you mention:
https://github.com/SBNSoftware/sbndcode/blob/978efb9437a93394d4490ab696257d4c5ca24b78/sbndcode/OpDetSim/opDetDigitizerWorker.cc#L164-L165

repeats for the non-lite part of the code:
https://github.com/SBNSoftware/sbndcode/blob/978efb9437a93394d4490ab696257d4c5ca24b78/sbndcode/OpDetSim/opDetDigitizerWorker.cc#L227

I believe the quickest way to solve this is to split the pmt `if` into two, one for coated and another for non-coated. That way we only call `CreateDirectPhotonMapLite(directPhotonsOnPMTS, photon_handles);` when is necessary. 

But this might be a good chance to go in and further refactor the code, quite frankly I've never been to keen about all those `if` and `else if`s.

**Comment by wesketchum** [comment]
Has this been resolved/fixed in sbndcode?

**Comment by fjnicolas** [comment]
Fixed in the PR #43
