### ISSUE TITLE
Neutrino Time of Flight Propagation is not correct applied and Dirt Flux

### ISSUE THREAD

**Issue by VCLanNguyen** [SBNSoftware/sbndcode#410]
**ISSUE:** 
Neutrino time of flight propagation have been tested and validated using the standard flux (detector volume size only). 
The same method is used for dirt flux however it is not applied correct.

For example, dumping output in [GENIE2Art](https://github.com/NuSoftHEP/nugen/blob/develop/nugen/EventGeneratorBase/GENIE/GENIE2ART.cxx#L233-L240) when filling vtx t of an MCTruth object

Standard flux neutrino ToF output: We get the expected ToF of ~110 m baseline / speed of light. 
```
addGenieVtxTime is true if true, added 379.454 ns GENIE Vtx (t = 3.79454e-07, x = 1.80196, y = -0.08$
7323, z = 3.68055)
>>>>>> MCTruth vtx t before = 1007.45
```
Dirt flux neutrino ToF output: We get bonker numbers.
```
addGenieVtxTime is true if true, added 48.653 ns GENIE Vtx (t = 4.8653e-08, x = -1.5254, y = 0.575829, z = -3.41629)
>>>>>> MCTruth vtx t before = 1464.03
>>>>>> MCTruth vtx t after = 1512.68
```

More details can be found on [sbn-db 34718](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=34718)

**STEP TO REPRODUCE**

 In our dirt simulation we use rockbox and the gSimple flux window is placed at Z=0 (SBND front face) and is then pushed back 18 m with [FluxUpstreamZ](https://github.com/SBNSoftware/sbndcode/blob/6346acf2c988acff59224156d4053bb294b76121/sbndcode/LArSoftConfigurations/gen/genie_sbnd.fcl#L330).

The gSimple flux files that contain the neutrino time at the window is located here: `/cvmfs/sbnd.osgstorage.org/pnfs/fnal.gov/usr/sbnd/persistent/stash/fluxFiles/bnb/BooNEtoGSimple/configL-v1/oct2023/neutrinoMode`

The fcl parameter `AddGenieVtxTime` is set to [true](https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/LArSoftConfigurations/gen/genie_sbnd.fcl#L314), which is default on sbndcode.

Setup:
```
source /cvmfs/sbnd.opensciencegrid.org/products/sbnd/setup_sbnd.sh
setup sbndcode v09_82_01 -q e26:prof
```

Fcl for standard (detector) simulation:
```
lar -c prodgenie_nu_spill_tpc_sbnd.fcl -n 10
```

Fcl for running SBND dirt simulation:
```
#include "prodoverlay_corsika_cosmics_proton_genie_rockbox_sce.fcl"

physics.producers.generator.FluxSearchPaths: "/cvmfs/[sbnd.osgstorage.org/pnfs/fnal.gov/usr/sbnd/persistent/stash/fluxFiles/bnb/BooNEtoGSimple/configL-v1/oct2023/neutrinoMode](http://sbnd.osgstorage.org/pnfs/fnal.gov/usr/sbnd/persistent/stash/fluxFiles/bnb/BooNEtoGSimple/configL-v1/oct2023/neutrinoMode)"
physics.producers.generator.FluxFiles: [ "gsimple_april07_baseline_*_redecay_wkaonwgh.root” ]
```

**Comment by sjgardiner** [comment]
@miquelnebot @ibsafa We'll need a new build of GENIE (either an official upgrade or a patched ups product) to resolve this one. Let me see if we can get an official tag soon. If not, let's work together to explore other options.

**Comment by VCLanNguyen** [comment]
Would getting a new GENIE tag is fast enough to cut a release for production (in 2-3 weeks time)?

**Comment by bear-is-asleep** [comment]
@VCLanNguyen was this fixed? Can I close the issue?

**Comment by bear-is-asleep** [comment]
To be fixed by `larsoft v09_91_00` [here](https://cdcvs.fnal.gov/redmine/issues/28747 )
