### ISSUE TITLE
Keep only MCParticles that cross cryostat and CRT 

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbndcode#434]
Now that https://github.com/SBNSoftware/sbndcode/issues/175 has been resolved, we should test and eventually adopt a new fcl configuration where we only keep MCParticles in certain volumes.

This is what we were using with the legacy larg4:
https://github.com/SBNSoftware/sbndcode/blob/0cbd52f1f7d0b6d21460ec1190ac6487d9f14bc6/sbndcode/JobConfigurations/standard/g4/legacy/legacy_g4_sbnd.fcl#L100-L102

**Comment by bear-is-asleep** [comment]
Should this be the default? From the ML reco side at least this shouldn't be an issue. We can set it [here](https://github.com/SBNSoftware/sbndcode/blob/b1b597db11e3987867493c8b57cb2fd0ba439bb3/sbndcode/LArG4/larg4_services_sbnd.fcl#L71).
