### ISSUE TITLE
Number of Wires

### ISSUE THREAD

**Issue by marcodeltutto** [SBNSoftware/sbndcode#438]
The current number of wires in the simulation is incorrect. 

This issue was identified by @mstancar and @absolution1 in the v1 geometry, and again by @tomjunk in v2. 

Since for the Y plane there are no wires in the middle of the 2 APAs, what was meant to be done in the past was to add more Y wires and flag the ones in the middle as dead. But, in the current version of the geometry, this is not the case, we don't have more wires but are still turning off some of the wires, having in the end fewer channels than in reality. This is also true for the induction wires, where the no-existent wires are at the corners.

The dead wires were added with geometry v01_05, and the following table summarizes the number of wires in v01_05, v02_00 (current), and in reality.

<img width="484" alt="image" src="https://github.com/SBNSoftware/sbndcode/assets/17006198/530b3a01-917e-4b25-bf3a-ea49c40a913b">

While in v01_05, the "dead" wires were in the correct position (although leading to an incorrect number of total wires), in the current v02_00 they end up in the wrong positions, as can be seen in the following plots, showing the wires on plane 0, 1, 2, and indicating the wires flagged as "dead" in red.

**v01_05**
![wires_01_05](https://github.com/SBNSoftware/sbndcode/assets/17006198/5fb871fe-b8a2-4cc6-97f0-27eb9ed01097)

**v02_00**
![wires](https://github.com/SBNSoftware/sbndcode/assets/17006198/0ceef0f7-cfa7-4d60-8023-dc032428d35e)

**Comment by lkashur** [comment]
Feature branch has been created for collection plane wire fix --> [https://github.com/SBNSoftware/sbndcode/tree/feature/lkashur_geo_wires2](https://github.com/SBNSoftware/sbndcode/tree/feature/lkashur_geo_wires2)

In this branch, the number of collection plane wires has been increased to 1670.  The relevant GDML files are in `sbndcode/Geometry/gdml/` and titled
1. sbnd_v02_02_base.gdml
2. sbnd_v02_02.gdml
3. sbnd_v02_02_nowires.gdml

Remaining to-do items:
- Edit "bad channels" list at `sbndcode/Utilities/badchannels_sbnd.fcl`.  We need to add six wires to the list to account for the gap between APAs.  Another two wires need to be added in the center of each APA (one per wire comb).  This brings us to num. simulated wires = 1670 - 8 = 1662, which is equivalent to the real number of collection plane wires.  **Input is needed from TPC/sim. experts to make sure we are adding the correct wires to the "bad" list.**
- Validation..make sure changes do not break anything

**Comment by absolution1** [comment]
Hi @lkashur 
As a heads up, there's a PR to add bad channels for data.  Amongst other things it already includes the combs channels.  These will need to be updated.  It's probably worth waiting for the PR to be merged (or to merge my branch with yours now) so that we don't become desynchronised.

**Comment by bear-is-asleep** [comment]
[PR 487](https://github.com/SBNSoftware/sbndcode/pull/487)
