### ISSUE TITLE
Update SBND fcl files for 2020A production

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbndcode#47]
I have this from a message/quick look from Joseph. Don't know if it's accurate.

> 1. standard_g4_sbnd.fcl --> Electronlifetime: 3000
> 2. standard_detsim_sbnd.fcl --> Electronlifetime: 3000
> 3. standard_reco2_sbnd.fcl -->  Electronlifetime: 3000
> 4. Need to add SCE effects to SBND in-time generation
> 5. standard_reco2_sbnd.fcl --> "CalAreaConstants:  [ 0.02354, 0.02130, 0.02354 ]" Doesn't match DocDB 18991

I'd assign this to Mike Mooney, but don't see him as a member of SBNSoftware. So, sorry @jzennamo.

**Comment by absolution1** [comment]
Those numbers do indeed describe the parameter state for sbndcode.  
The calo constants were last changed 4 years ago.

The lifetime should only need tweaking here: https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/Utilities/detectorproperties_sbnd.fcl#L8

and the calo constants should only need tweaking here:
https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/LArSoftConfigurations/calorimetry_sbnd.fcl#L9

**Comment by jzennamo** [comment]
OK, I changed these to the values we agreed to. Question, how would we like these tested? 

I can check the fcl dumps for all the production fcls to check. Anything else?

**Comment by wesketchum** [comment]
Checking fcl dumps sounds like a good first thing.

Calorimetry is maybe the end result to check then? Not sure what the best way to test this is otherwise.

@jzennamo, do you have a branch/pull request nearing ready that we can link? Just to keep track.

**Comment by jzennamo** [comment]
I am writing up a quick script to dump all our production fcls so I can quickly check. 

I'll also have to work with @gputnam to address #4 above

**Comment by jzennamo** [comment]
According to @gputnam the SBND space-charge configurations are incorrect, we should check that before closing this issue.

**Comment by gputnam** [comment]
I think the space charge config is correct -- sorry -- it was a different piece of the config that I thought was wrong.

I think the space charge piece of the config looks ine.

**Comment by jzennamo** [comment]
OK! Good to know, I added this feature branch that should gobble that up then:
https://github.com/SBNSoftware/sbndcode/compare/feature/zennamo_intime_with_sce

if @gputnam thinks it is correct I'll request a pull-request and we can close this issue

**Comment by jzennamo** [comment]
OK, @gputnam has addressed the 4th problem above in this PR https://github.com/SBNSoftware/sbndcode/pull/51 

I'll close this
