### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by bear-is-asleep** [SBNSoftware/sbndcode#488]
## I'm submitting a ...

- [x] bug report
- [ ] feature request

## Checklist
- [x] I've added a label
- [x] Assigned a reviewer

**Comment by PetrilloAtWork** [comment]
Very quick resolution. Keep the good work!

**Comment by bear-is-asleep** [comment]
> Very quick resolution. Keep the good work!

thanks haha it's easy to solve the issue when it doesn't exist!

**Comment by PetrilloAtWork** [comment]
I would have said the exact opposite: hard to convince people that the issues they perceive do not exist.

**Comment by bear-is-asleep** [comment]
I guess I'm confused by your comment. This is a template issue from that opens everytime an issue is opened in this repo. This test was just to show that it would show up properly if I opened an issue. So if you were to open an issue now, this template would appear still.
