### ISSUE TITLE
Ortho3D and Display3D views are broken

### ISSUE THREAD

**Issue by ikatza** [SBNSoftware/sbndcode#56]
The last version that I found to be working is `v08_55_00`.

This commit a8346043 by @absolution1 changed the simulations services to address an issue with the noise service. Whilst it did manage to get back the event display, it didn't fix the Ortho3D and Display3D views.

Unfortunately the current version of sbndcode `v09_08_00` introduce new changes that prevent files produced with it to be displayed with a previous version of the event display.

**Comment by absolution1** [comment]
Hi @ikatza IIRC I dropped the simulation services block for the generic services block.  It is a little bizarre that the simulation services block is needed for those displays.

Anyway, the most correct-est thing to do would be to convince the display not to care about the noise service when using the full simulation service block.

**Comment by ikatza** [comment]
Confirm that commenting out 

```
# NoiseModel:                @local::sbnd_uboonedatadrivennoiseservice
```

from `LArSoftConfigurations/simulationservices_sbnd.fcl` does bring back the Ortho3D and Display 3D views.

I'll come up with something neater.

**Comment by ikatza** [comment]
I've opened PR #57 to fix this issue.
