### ISSUE TITLE
sbndPDMapAlg causing sbndcode c7 builds to fail.

### ISSUE THREAD

**Issue by ascarff** [SBNSoftware/sbndcode#59]
The CI has picked up fails in the c7 builds coming from sbndPDMapAlg. Looks like it's a simple fix to the function. Error is:

`2107: In file included from /scratch/workspace/sbnd_ci/label_exp/SLF7/label_exp2/swarm/SBND/srcs/sbndcode/sbndcode/OpDetSim/opDetDigitizerWorker.cc:4:
2108: In file included from /scratch/workspace/sbnd_ci/label_exp/SLF7/label_exp2/swarm/SBND/srcs/sbndcode/sbndcode/OpDetSim/opDetDigitizerWorker.hh:17:
2109: /scratch/workspace/sbnd_ci/label_exp/SLF7/label_exp2/swarm/SBND/srcs/sbndcode/sbndcode/OpDetSim/sbndPDMapAlg.hh:56:10: error: 'isPDType' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
2110:     bool isPDType(size_t ch, std::string pdname) const;
2111:          ^
2112: /scratch/workspace/sbnd_ci/label_exp/SLF7/label_exp2/swarm/SBND/srcs/sbncode/sbncode/OpDet/PDMapAlg.h:33:18: note: overridden virtual function is here
2113:     virtual bool isPDType(size_t ch, std::string pdname) const
2114:                  ^`

**Comment by ikatza** [comment]
PR #60 fixes this.

**Comment by ascarff** [comment]
PR #60 merged. Closing.
