### ISSUE TITLE
[MCP2020A] Apparent Issue with PMT OpHits

### ISSUE THREAD

**Issue by gputnam** [SBNSoftware/sbndcode#61]
While testing the production for MCP 2020A, we encountered an issue where the simple flash matching (Iker's) was not producing output. We traced this to an issue where all of the OpHit's from PMT's are produced with "0" filled in every variable in each hit as seen by Iker's module.

From my view, it seems like we should hold off on production until we can confirm the integrity of the OpHits.

**Comment by ikatza** [comment]
Hey mate, thanks for testing this. It's a quick fix, had to rename the OpHitProducer. Fix is on #66.
