### ISSUE TITLE
Beam spot is in the wrong place

### ISSUE THREAD

**Issue by mstancar** [SBNSoftware/sbndcode#79]
Beam axis should be at x=-74 cm in the larsoft SBND detector coordinate system based on the latest survey measurements.
Currently it is at x=+50cm

Cross check of this number is ongoing with the data taken with the CRT panels in the pit.

**Comment by jzennamo** [comment]
Thanks for pointing this out @mstancar. Who is cross-checking this number with the CRT panels? Just so we can follow-up

**Comment by mstancar** [comment]
That would be Igor and Ornella

**Comment by marcodeltutto** [comment]
Update: Zarko is producing new gsimple files with the correct X offset.
