### ISSUE TITLE
XARAPUCA Waveform Simulation doesn't distinguish electronics

### ISSUE THREAD

**Issue by ikatza** [SBNSoftware/sbndcode#80]
There are two distinct electronics used in SBND to readout XARAPUCAS: DAPHNE electronics and APSAIA+CAEN v1730. 

Their behaviour is different, for instance their single PE response and digitisation clock.

I suggest to add a field on the json PDS map:
https://github.com/SBNSoftware/sbndcode/blob/develop/sbndcode/OpDetSim/sbnd_pds_mapping.json

Something like `"electronics": "apsaia"/"daphne"` It's enough to add the field on the xarapuca channels
```
{
  "channel": 0,
  "pd_type": "xarapuca_vis",
  "pds_box": 0,
  "sensible_to_vis": true,
  "sensible_to_vuv": false,
  "tpc": 0,
  "electronics": "daphne"
},
```

This issue is related to which would also need to be resolved: https://github.com/SBNSoftware/sbndcode/issues/78

**Comment by jicrespo** [comment]
@rodralva is going to look into this.

**Comment by wesketchum** [comment]
@jicrespo @rodralva any update on this?

**Comment by rodralva** [comment]
Hi Wesley! Yes, I've been [working on the issue](https://sbn-docdb.fnal.gov/cgi-bin/sso/ShowDocument?docid=22430) and I'll do a pull request with the frequency and the test XArapuca response updates this week or the next.

**Comment by wesketchum** [comment]
thanks @rodralva !!

The sooner the better so we can get it reviewed and verify it passes all tests ahead of our aimed release deadline of 13 Aug. Looking forward to seeing this all in!
